### ISSUE TITLE
Failed compilation - AW9523 and ESP32 S3

### ISSUE THREAD

**Issue by imar014** [jenscski/esphome-components#6]
Am using ESPHome Device Builder
Current version: 2025.3.3

Recurrent error on compilation as below:

src/main.cpp:333:55: error: invalid new-expression of abstract class type 'esphome::aw9523::AW9523GPIOPin'
  333 |   aw9523_aw9523gpiopin_id = new aw9523::AW9523GPIOPin();
      |                                                       ^
In file included from src/esphome.h:16,
                 from src/main.cpp:3:
src/esphome/components/aw9523/aw9523_gpio_pin.h:12:15: note:   because the following virtual functions are pure within 'esphome::aw9523::AW9523GPIOPin':
   12 |         class AW9523GPIOPin : public GPIOPin
      |               ^~~~~~~~~~~~~
In file included from src/esphome/core/hal.h:4,
                 from src/esphome/core/application.h:7,
                 from src/esphome/components/api/api_connection.h:9,
                 from src/esphome.h:3:
src/esphome/core/gpio.h:61:23: note:     'virtual esphome::gpio::Flags esphome::GPIOPin::get_flags() const'
   61 |   virtual gpio::Flags get_flags() const = 0;_

The same error occurs on GPIOPout as well

Does compile when only using output function

YAML File

esphome:
  name: stamp-plc
  friendly_name: stamp_plc

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rW0iE0B/UutLSMKQfhvFVv0o2yTMIj82DXmbog31MNQ="

ota:
  - platform: esphome
    password: "87ec91da43ccb3744fbacbf2bd97e3e6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stamp-Plc Fallback Hotspot"
    password: "juaxQ7jLQ8L2"

captive_portal:

external_components:
  - source: github://jenscski/esphome-components@main
    components: [aw9523]

i2c:
  sda: GPIO13
  scl: GPIO15
  scan: false

aw9523:
  - id: aw9523_1
    address: 0x59
    divider: 3
    latch_inputs: true

binary_sensor:
  - platform: gpio
    name: "AW9523 Pin #14"
    pin:
      aw9523: aw9523_1
      number: 14
      mode:
        input: true
      inverted: true

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO8
  miso_pin: GPIO9

display:
  - platform: ili9xxx
    model: ST7789V
    dimensions:
      height: 240
      width: 135
      offset_height: 40
      offset_width: 52
    dc_pin: GPIO06
    cs_pin: GPIO12
    reset_pin: GPIO03
    invert_colors: false
    show_test_card: true
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 20

**Comment by Beormund** [comment]
@imar014, I managed to get the relays working on the M5StamPLC via the AW9523B. Pin 3 needs to be pulled high to enable the chip:

```yaml
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 1000
    then:
      - lambda: |-
          pinMode(03, OUTPUT);
          digitalWrite(03, HIGH);

# Import custom component from GitHub
external_components:
  - source: github://jenscski/esphome-components@main
    components: [aw9523]    

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
```
You can then set up the relays like so:

```yaml
# Configuration of GPIO Expander component
aw9523:
  - id: aw9523_1
    address: 0x59
    divider: 3
    latch_inputs: true

switch:
  - platform: gpio
    name: "Relay 1"
    pin:
      aw9523: aw9523_1
      number: 0
      mode:
        output: true
  - platform: gpio
    name: "Relay 2"
    pin:
      aw9523: aw9523_1
      number: 1
      mode:
        output: true
  - platform: gpio
    name: "Relay 3"
    pin:
      aw9523: aw9523_1
      number: 2
      mode:
        output: true
  - platform: gpio
    name: "Relay 4"
    pin:
      aw9523: aw9523_1
      number: 3
      mode:
        output: true
```
